spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME:crudwithtdd}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: ture
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

jwt:
  secret-key: ${SECRET_KEY}

  access-exp: ${ACCESS_EXP:1800}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error